services:
    api: 
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile

        command: /start
        volumes:
            - .:/app
            - myapp_djangostarter_static_volume:/app/staticfiles
            - myapp_djangostarter_media_volume:/app/mediafiles
        
        env_file:
            - app/.env
        depends_on:
            - postgres-db
            - elasticsearch
            - redis

        networks:
            - djangostarter-network

    postgres-db: 
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        volumes:
            - myapp_djangostarter_postgres_data:/var/lib/postgresql/data/
        env_file:
            - app/.env

        networks:
            - djangostarter-network

    redis:
        image: redis:6.0.9-alpine
        container_name: myapp-redis
        ports:
        - "6379:6379"
        networks:
        - djangostarter-network

    celery_worker:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-celeryworker
        volumes:
            - .:/app
        env_file:
            - app/.env
        depends_on:
            - redis
            - postgres-db
        networks:
            - djangostarter-network

    flower:
        build: 
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-flower
        volumes:
            - .:/app
        env_file:
            - app/.env
        ports:
            - 5557:5555
        depends_on:
            - redis
            - postgres-db
        networks:
            - djangostarter-network
             

    nginx:
        restart: always
        depends_on:
            - api
        build: 
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            # - 443:443 # uncomment this line in production
        networks:
            - djangostarter-network
        # volumes:
        #     - /etc/letsencrypt:/etc/letsencrypt # uncomment this line in production


    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        volumes:
            - myapp_djangostarter_elastic_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - 9200:9200

        networks:
            - djangostarter-network

    

networks:
    djangostarter-network:
        driver: bridge

volumes:
    myapp_djangostarter_postgres_data:
    myapp_djangostarter_static_volume:
    myapp_djangostarter_media_volume:
    myapp_djangostarter_elastic_data:       

